#!/bin/bash
	case "$1" in
		""|"start" )
		 echo "Starting LEMP =)"
			sudo service mysql start
			sudo service php7.0-fpm start
			sudo service apache2 stop
			sudo service nginx start
			sudo service ssh start
			echo "Have a good job!"
		;;
		"restart"|"-r" )
			echo "Restarting LEMP"		
                        sudo service nginx restart
                        sudo service php7.0-fpm restart
                        sudo service mysql restart
                        sudo service ssh restart
		;;
		"stop")
		 echo "Stopping LEMP =("
                        sudo service nginx stop
                        sudo service php7.0-fpm stop
                        sudo service mysql stop
                        sudo service ssh stop
			echo "bye!"
		;;
	esac
